### PR TITLE
Update SPECIFICATION.md

### PR DESCRIPTION
**Pull request by x87**
minor changes; I believe *jump* is a randomly guessed name and a correct form of GOTO must be used

### CODE REVIEW

**Comment by x87** [comment]
@thelink2012 please take a look

**Comment by thelink2012** [comment]
Thanks for the check up!

Regarding the jump, we need to a term to refer to any command which changes the control-flow in a way that code is *not coming back there*.

The **RETURN** command is considered to be a jump. As such, the execution of a **RETURN** leaving a lexical scope deactivates it.

Not sure though if *jump* is the best term or the definition is clear enough. But I think *goto* is too restrict.

**Comment by x87** [comment]
OK, I've got the point. A formal term for that would be **unconditional branching command** with *jump command* or *goto command* used as synonyms. 

That paragraph could be written like:

A command is said to perform a **unconditional branching** if it changes the *flow of control* irreversibly.

However I'm OK to revert it back to jump. What do you think?

**Comment by thelink2012** [comment]
We'd get confused again because of commands that perform conditional branches, but are still irreversible. There is also *one-way transfer of control*, but it suffers from the same issue.

Yeah, I think we should left it as jump unless a better term is found :)

**Comment by x87** [comment]
Done

**Comment by thelink2012** [comment]
Just something I've read recently that may be relevant: LLVM calls instruction ending a basic block *terminator instructions*.

**Comment by thelink2012** [comment]
The GTA2script Manual from DMA uses the term jump very often, although `GOSUB` is refereed to as a jump too...

**Comment by thelink2012** [comment]
This is now an issue #2.

**Pull request merged**
